import { UserRole } from '@prisma/client';

export type AppUser = {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  email: string;
  name: string;
  role: UserRole;
  avatarUrl: string | null;
  bio: string | null;
  skills: string[] | null;
  rate: number | null;
  phoneNumber: string | null;
  location: string | null;
  state: string | null;
  district: string | null;
  latitude: number | null;
  longitude: number | null;
  coverageRadius: number | null;
  acceptsOutstation: boolean;
  rating?: number | null;
  reviewCount?: number | null;
  isAvailable: boolean;
  bankCode?: string | null;
  bankAccount?: string | null;
  bankHolderName?: string | null;
  bankVerified?: boolean;
  level: string;
  totalCompletedJobs: number;
  totalReviews: number;
  replyRate?: number | null;
};
