const Map<String, List<String>> malaysiaStatesAndDistricts = {
  'Johor': [
    'Batu Pahat',
    'Johor Bahru',
    'Kluang',
    'Kota Tinggi',
    'Kulai',
    'Mersing',
    'Muar',
    'Pontian',
    'Segamat',
    'Tangkak'
  ],
  'Kedah': [
    'Baling',
    'Bandar Baharu',
    'Kota Setar',
    'Kuala Muda',
    'Kubang Pasu',
    'Kulim',
    'Langkawi',
    'Padang Terap',
    'Pendang',
    'Pokok Sena',
    'Sik',
    'Yan'
  ],
  'Kelantan': [
    'Bachok',
    'Gua Musang',
    'Jeli',
    'Kota Bharu',
    'Kuala Krai',
    'Machang',
    'Pasir Mas',
    'Pasir Puteh',
    'Tanah Merah',
    'Tumpat'
  ],
  'Melaka': ['Alor Gajah', 'Jasin', 'Melaka Tengah'],
  'Negeri Sembilan': [
    'Jelebu',
    'Jempol',
    'Kuala Pilah',
    'Port Dickson',
    'Rembau',
    'Seremban',
    'Tampin'
  ],
  'Pahang': [
    'Bentong',
    'Bera',
    'Cameron Highlands',
    'Jerantut',
    'Kuantan',
    'Lipis',
    'Maran',
    'Pekan',
    'Raub',
    'Rompin',
    'Temerloh'
  ],
  'Perak': [
    'Bagan Datuk',
    'Batang Padang',
    'Hilir Perak',
    'Hulu Perak',
    'Kampar',
    'Kerian',
    'Kinta',
    'Kuala Kangsar',
    'Larut, Matang dan Selama',
    'Manjung',
    'Muallim',
    'Perak Tengah'
  ],
  'Perlis': ['Perlis'],
  'Pulau Pinang': [
    'Barat Daya',
    'Seberang Perai Selatan',
    'Seberang Perai Tengah',
    'Seberang Perai Utara',
    'Timur Laut'
  ],
  'Sabah': [
    'Beaufort',
    'Beluran',
    'Keningau',
    'Kinabatangan',
    'Kota Belud',
    'Kota Kinabalu',
    'Kota Marudu',
    'Kuala Penyu',
    'Kudat',
    'Kunak',
    'Lahad Datu',
    'Nabawan',
    'Papar',
    'Penampang',
    'Putatan',
    'Pitas',
    'Ranau',
    'Sandakan',
    'Semporna',
    'Sipitang',
    'Tambunan',
    'Tawau',
    'Tenom',
    'Tongod',
    'Tuaran'
  ],
  'Sarawak': [
    'Asajaya',
    'Bau',
    'Belaga',
    'Betong',
    'Bintulu',
    'Bukit Mabong',
    'Dalat',
    'Daro',
    'Julau',
    'Kabong',
    'Kanowit',
    'Kapit',
    'Kuching',
    'Lawas',
    'Limbang',
    'Lubok Antu',
    'Lundu',
    'Miri',
    'Marudi',
    'Matu',
    'Meradong',
    'Mukah',
    'Pakan',
    'Pusa',
    'Samarahan',
    'Saratok',
    'Sarikei',
    'Sebauh',
    'Selangau',
    'Serian',
    'Sibu',
    'Simunjan',
    'Song',
    'Sri Aman',
    'Subis',
    'Tanjung Manis',
    'Tatau',
    'Tebedu'
  ],
  'Selangor': [
    'Gombak',
    'Hulu Langat',
    'Hulu Selangor',
    'Klang',
    'Kuala Langat',
    'Kuala Selangor',
    'Petaling',
    'Sabak Bernam',
    'Sepang'
  ],
  'Terengganu': [
    'Besut',
    'Dungun',
    'Hulu Terengganu',
    'Kemaman',
    'Kuala Nerus',
    'Kuala Terengganu',
    'Marang',
    'Setiu'
  ],
  'W.P. Kuala Lumpur': ['Kuala Lumpur'],
  'W.P. Labuan': ['Labuan'],
  'W.P. Putrajaya': ['Putrajaya']
};
